sonar.projectKey=crypto-sma-crossover-laravel-vue
sonar.sources=backend/app,frontend/src,docker
sonar.exclusions=backend/vendor/**,frontend/node_modules/**,frontend/dist/**,frontend/.pnpm-store/**
sonar.tests=backend/tests
sonar.php.coverage.reportPaths=backend/coverage.xml
sonar.coverage.exclusions=frontend/src/**/*,backend/app/Models/**/*,backend/app/Providers/**/*,backend/app/Http/Kernel.php,backend/app/Http/Middleware/**/*
