services:
  postgres:
    image: postgres:17-alpine
    container_name: crossover_postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: crossover_redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: crossover_backend
    volumes:
      - ../backend:/var/www/html
    working_dir: /var/www/html
    env_file:
      - .env
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      CACHE_STORE: redis
      REDIS_HOST: redis
      APP_PASSWORD: ${APP_PASSWORD}
    ports:
      - "8000:8000"
    command: php artisan serve --host=0.0.0.0 --port=8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    container_name: crossover_frontend
    user: root
    volumes:
      - ../frontend:/var/www/html
      - /var/www/html/node_modules
    environment:
      VITE_API_BASE_URL: "http://localhost:8000"
      CI: "true"
    ports:
      - "5173:5173"
    command: sh -c "chown -R node:node /var/www/html/node_modules && su node -c 'pnpm run dev'"
    depends_on:
      - backend


volumes:
  postgres_data:
